### PR TITLE
🍏 Create test with custom description

### PR DESCRIPTION
**Pull request by onniaa**
- Allow users to name the new suite of the composed test
- Search existing suites asynchronously

### CODE REVIEW

**Review by Gilad-Gur-Andelman — APPROVED** [review]
Very well done 👍

**Comment by Gilad-Gur-Andelman** [comment]
Windows Build: 1. [Setup.exe](https://output.circle-artifacts.com/output/job/c62d0fa8-9c27-4bed-811c-325274c58220/artifacts/0/out/make/squirrel.windows/x64/RELEASES) 2. [.zip](https://output.circle-artifacts.com/output/job/c62d0fa8-9c27-4bed-811c-325274c58220/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.1.8.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/4ff7cf99-6b75-45f2-a91f-31a56fc452ae/artifacts/0/out/make/Loadmill-3.1.9-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/4ff7cf99-6b75-45f2-a91f-31a56fc452ae/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.9.zip)

**Comment by Gilad-Gur-Andelman** [comment]
Windows Build: 1. [Setup.exe](https://output.circle-artifacts.com/output/job/d107573c-f247-45ae-81f0-ba33e4de2b84/artifacts/0/out/make/squirrel.windows/x64/RELEASES) 2. [.zip](https://output.circle-artifacts.com/output/job/d107573c-f247-45ae-81f0-ba33e4de2b84/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.1.9.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/26222e4f-1609-4631-9ef3-155907d7f113/artifacts/0/out/make/Loadmill-3.1.9-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/26222e4f-1609-4631-9ef3-155907d7f113/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.9.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/a36ba899-7d6c-4c65-8d23-ec9eb6bc0a58/artifacts/0/out/make/Loadmill-3.1.9-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/a36ba899-7d6c-4c65-8d23-ec9eb6bc0a58/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.9.zip)

**Comment by Gilad-Gur-Andelman** [comment]
Windows Build: 1. [Setup.exe](https://output.circle-artifacts.com/output/job/39b4a262-5bc0-455d-8f5b-7df0dfd16498/artifacts/0/out/make/squirrel.windows/x64/RELEASES) 2. [.zip](https://output.circle-artifacts.com/output/job/39b4a262-5bc0-455d-8f5b-7df0dfd16498/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.1.9.zip)

**Review by yigaldviri — APPROVED** [review]

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/eae7a065-4064-430e-ba6f-ec0ec56f003e/artifacts/0/out/make/Loadmill-3.1.9-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/eae7a065-4064-430e-ba6f-ec0ec56f003e/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.9.zip)

**Comment by Gilad-Gur-Andelman** [comment]
Windows Build: 1. [Setup.exe](https://output.circle-artifacts.com/output/job/66f3a556-1abe-4143-9e47-2ee54dd4aee8/artifacts/0/out/make/squirrel.windows/x64/RELEASES) 2. [.zip](https://output.circle-artifacts.com/output/job/66f3a556-1abe-4143-9e47-2ee54dd4aee8/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.1.9.zip)

**Pull request merged**
