### PR TITLE
🧑‍🚀 Windows Setup.exe Filename

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/ef89134d-e275-416a-8176-ccea7f88e900/artifacts/0/out/make/Loadmill-3.1.6-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/ef89134d-e275-416a-8176-ccea7f88e900/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.6.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/699c7080-d942-416a-bf5b-c7b8b83acb64/artifacts/0/out/make/Loadmill-3.1.6-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/699c7080-d942-416a-bf5b-c7b8b83acb64/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.6.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/a76495b5-32b8-4260-b336-da467d021882/artifacts/0/out/make/Loadmill-3.1.6-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/a76495b5-32b8-4260-b336-da467d021882/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.1.6.zip)

**Comment by Gilad-Gur-Andelman** [comment]
Windows Build: 1. [Setup.exe](https://output.circle-artifacts.com/output/job/957b587a-6a00-430c-b84a-aa3ec00754e9/artifacts/0/out/make/squirrel.windows/x64/RELEASES) 2. [.zip](https://output.circle-artifacts.com/output/job/957b587a-6a00-430c-b84a-aa3ec00754e9/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.1.6.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
