### PR TITLE
⚛️📝 Log only using electron-log

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/e99844e1-e544-4e3a-a50f-8d5406d3f2ff/artifacts/0/out/make/Loadmill-3.3.19-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/e99844e1-e544-4e3a-a50f-8d5406d3f2ff/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.19.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/b869db7c-db14-494f-b487-3cbf2c445891/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.19-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/b869db7c-db14-494f-b487-3cbf2c445891/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.19.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/787573d8-5207-4a43-9f53-58cee0ef30c0/artifacts/0/out/make/Loadmill-3.3.20-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/787573d8-5207-4a43-9f53-58cee0ef30c0/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.20.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/e1a4dd63-110b-4249-bda1-04e0015ed0aa/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.20-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/e1a4dd63-110b-4249-bda1-04e0015ed0aa/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.20.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
