### PR TITLE
⬆️ Import Har

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/3fca2450-85d1-4c89-a96d-8af28e73dea2/artifacts/0/out/make/Loadmill-3.0.3-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/3fca2450-85d1-4c89-a96d-8af28e73dea2/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.3.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/0abb5287-b523-43eb-8496-78e1e4f2298d/artifacts/0/out/make/Loadmill-3.0.3-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/0abb5287-b523-43eb-8496-78e1e4f2298d/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.3.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/3ca981b1-5f30-487e-8444-8c70f6a3798b/artifacts/0/out/make/Loadmill-3.0.3-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/3ca981b1-5f30-487e-8444-8c70f6a3798b/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.3.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/efc896a3-8547-4ac6-b83d-ed73e306ded4/artifacts/0/out/make/Loadmill-3.0.3-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/efc896a3-8547-4ac6-b83d-ed73e306ded4/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.3.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
