### PR TITLE
🔐 External Authentication

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/a4ac4259-8b68-4f84-9db8-2510593abc4a/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/a4ac4259-8b68-4f84-9db8-2510593abc4a/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/56eb9319-5c27-4d65-811b-cf08b0bd7b69/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/56eb9319-5c27-4d65-811b-cf08b0bd7b69/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/8934c42f-c164-409f-9ef2-b65183bfd780/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/8934c42f-c164-409f-9ef2-b65183bfd780/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/cfdf45a1-1c17-46d6-9cc8-8fc4a29eec10/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/cfdf45a1-1c17-46d6-9cc8-8fc4a29eec10/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/7d6234e2-e775-421d-94db-5c0faecdbf87/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/7d6234e2-e775-421d-94db-5c0faecdbf87/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/5196059f-8fa0-4442-8220-e57859a13ffb/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/5196059f-8fa0-4442-8220-e57859a13ffb/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/07715043-c07f-4ef4-a7bd-09f8787d6a42/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/07715043-c07f-4ef4-a7bd-09f8787d6a42/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/43563073-88cb-439a-a0c9-073a1532ccb1/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/43563073-88cb-439a-a0c9-073a1532ccb1/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/8bd49c9d-4d5f-4320-82a6-0a96c8f1bb81/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/8bd49c9d-4d5f-4320-82a6-0a96c8f1bb81/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/af857786-9c60-45e2-ab87-e1bbb0326a49/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/af857786-9c60-45e2-ab87-e1bbb0326a49/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/9809ab39-48ae-45e2-a688-58fda25cda42/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/9809ab39-48ae-45e2-a688-58fda25cda42/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/55f5fef2-3de3-49a4-8d8d-e74537ea64e1/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/55f5fef2-3de3-49a4-8d8d-e74537ea64e1/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/896d3fa6-3646-4d45-a2ab-4a8d3a007b37/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/896d3fa6-3646-4d45-a2ab-4a8d3a007b37/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/2eb329dc-e85e-42a7-9a61-819e77c3a081/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/2eb329dc-e85e-42a7-9a61-819e77c3a081/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/97c0ccda-1385-41d1-81f4-fee557f421cb/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/97c0ccda-1385-41d1-81f4-fee557f421cb/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/8be29741-c369-4df9-9347-48527f89596b/artifacts/0/out/make/Loadmill-3.2.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/8be29741-c369-4df9-9347-48527f89596b/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/fe86fa60-88bb-4d52-b686-982e0dacc401/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.2.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/fe86fa60-88bb-4d52-b686-982e0dacc401/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.2.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/c17a93da-afac-40bf-a762-2c5ccb5ecad4/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c17a93da-afac-40bf-a762-2c5ccb5ecad4/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/745c9337-90b5-46f9-9990-537f9831bd14/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/745c9337-90b5-46f9-9990-537f9831bd14/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/385d1fe3-42a0-463a-8463-e3a6ee21ed72/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/385d1fe3-42a0-463a-8463-e3a6ee21ed72/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/b061a0e2-33c5-4050-b24d-9f35578006af/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/b061a0e2-33c5-4050-b24d-9f35578006af/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/183a69b7-f6a3-4b66-84be-c7d4e97b56c3/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/183a69b7-f6a3-4b66-84be-c7d4e97b56c3/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/6af6a371-3138-4edd-a582-5fd940d9ad69/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/6af6a371-3138-4edd-a582-5fd940d9ad69/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/ec143323-4637-4e00-b64c-bf6c1b3d713e/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/ec143323-4637-4e00-b64c-bf6c1b3d713e/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/01f8f233-d23b-4fcf-9732-72005de0509f/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/01f8f233-d23b-4fcf-9732-72005de0509f/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/fb142d3b-2873-4d79-ba5f-16aad41c4d84/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/fb142d3b-2873-4d79-ba5f-16aad41c4d84/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/c9db8cf9-9475-49c5-8fe9-3bc3bb83bd1a/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c9db8cf9-9475-49c5-8fe9-3bc3bb83bd1a/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Review by yigaldviri — APPROVED** [review]

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/bf8d95e3-40d6-4993-a475-b027eaa72fff/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/bf8d95e3-40d6-4993-a475-b027eaa72fff/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/35d681ae-cf98-4dc0-8859-25a36dc6e4ea/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/35d681ae-cf98-4dc0-8859-25a36dc6e4ea/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Pull request merged**
