### PR TITLE
🛩🛟👁 Upgrade CircleCI macOS Config

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/4beb3271-99f6-43ab-8fb8-dd5b73829872/artifacts/0/out/make/Loadmill-3.3.18-arm64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/4beb3271-99f6-43ab-8fb8-dd5b73829872/artifacts/0/out/make/zip/darwin/arm64/Loadmill-darwin-arm64-3.3.18.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/4533ead1-1c7e-4384-aec0-b5edab4453b4/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.18-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/4533ead1-1c7e-4384-aec0-b5edab4453b4/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.18.zip)

**Review by yigaldviri — APPROVED** [review]

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/f20a8db4-9852-4776-8129-57aaa0da4039/artifacts/0/out/make/Loadmill-3.3.18-universal.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/f20a8db4-9852-4776-8129-57aaa0da4039/artifacts/0/out/make/zip/darwin/universal/Loadmill-darwin-universal-3.3.18.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/f9069d34-ced4-4b10-9a99-c7f262f4acd4/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.18-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/f9069d34-ced4-4b10-9a99-c7f262f4acd4/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.18.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/19377a58-53c7-46eb-9bea-e11a60714c82/artifacts/0/out/make/Loadmill-3.3.18-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/19377a58-53c7-46eb-9bea-e11a60714c82/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.18.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/92e35dfc-6ed6-4240-ac90-0f2bae5878f6/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.18-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/92e35dfc-6ed6-4240-ac90-0f2bae5878f6/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.18.zip)

**Pull request merged**
