### PR TITLE
🧚‍♂️ Windows Login

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/7a93fc73-80cd-4068-b8b8-858107ff265f/artifacts/0/out/make/Loadmill-3.3.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/7a93fc73-80cd-4068-b8b8-858107ff265f/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/d91a3d24-3107-4144-99cf-4f7ead096c98/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.0-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/d91a3d24-3107-4144-99cf-4f7ead096c98/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.0.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/1da6778c-7bba-45bc-8b50-6345df84b4c5/artifacts/0/out/make/Loadmill-3.3.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/1da6778c-7bba-45bc-8b50-6345df84b4c5/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/38b2c587-76a4-4ee8-a371-047611663336/artifacts/0/out/make/squirrel.windows/x64/desktop-app-3.3.1-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/38b2c587-76a4-4ee8-a371-047611663336/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/32cf574f-37b2-4128-b4e6-d26d0fc0cb95/artifacts/0/out/make/Loadmill-3.3.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/32cf574f-37b2-4128-b4e6-d26d0fc0cb95/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/260729cb-6cc4-48ad-9e12-3ced724fb040/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.1-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/260729cb-6cc4-48ad-9e12-3ced724fb040/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.1.zip)

**Review by onniaa — APPROVED** [review]

**Pull request merged**
