### PR TITLE
🔑 Auth Login - Allow Manual Token

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/af04f7b6-9188-49db-8e66-196e0df962f5/artifacts/0/out/make/Loadmill-3.3.3-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/af04f7b6-9188-49db-8e66-196e0df962f5/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.3.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/5938d475-bb1d-429a-82af-caaedcd23f3f/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.3-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/5938d475-bb1d-429a-82af-caaedcd23f3f/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.3.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/eac04e71-4a82-4fd7-baae-c80b78b17975/artifacts/0/out/make/Loadmill-3.3.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/eac04e71-4a82-4fd7-baae-c80b78b17975/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/d9c34f12-c7b0-4ffc-912d-be3901815e00/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.4-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/d9c34f12-c7b0-4ffc-912d-be3901815e00/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.4.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
