### PR TITLE
🔗🗿 Links To CircleCi Build Artifacts in PR

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
Artifacts are available here:

https://output.circle-artifacts.com/output/job/486d9be9-314c-4d54-9dbc-42cac528f412/artifacts/0/out/make/Loadmill-3.0.0-x64.dmg

https://output.circle-artifacts.com/output/job/486d9be9-314c-4d54-9dbc-42cac528f412/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.0.zip

**Comment by Gilad-Gur-Andelman** [comment]
✅ Build Artifacts are available here:

⬇️ [dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

⬇️ [zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
*** ✅ Build Artifacts are available here:

[⬇️ dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

[⬇️ zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
### ✅ Build Artifacts are available here:

[⬇️ dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

[⬇️ zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 👷‍♀️ Build 🗿 Artifacts are available here:

### 1. [🍏 dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 👷‍♀️ Build 🗿 Artifacts ✅ available 👇 here

### [🍏 dmg 🍎](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### [🤐 zip 🗜](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 👷‍♀️ Build 🗿 Artifacts ✅ available👇 here

### [🍏 dmg 🍎](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### [🤐   zip   🗜](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅ Build Artifacts are available here

#### 1. [ dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

#### 2. [🤐 zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅ Build Artifacts are available here

### 1. [🍎 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅ Build Artifacts are available here ��

### 1. [🍎 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅ Build Artifacts are available here 👇 

### 1. [🍎 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅  Build Artifacts are available here 👇 

### 1. [🍎 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## ✅  Build Artifacts are available here👇 

### 1. [🍎 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/Loadmill-3.0.1-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/900f9a85-ec41-40eb-9cd7-4d636c3e6f06/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.1.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/b9f57834-113d-47b9-856e-653029edaded/artifacts/0/out/make/Loadmill-3.0.0-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/b9f57834-113d-47b9-856e-653029edaded/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.0.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
