### PR TITLE
📃 Documentation

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/05c83111-ac7a-43c7-b487-07447da132fc/artifacts/0/out/make/Loadmill-3.0.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/05c83111-ac7a-43c7-b487-07447da132fc/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.4.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/6b30c854-b4ca-4700-aad1-073f3f8831f3/artifacts/0/out/make/Loadmill-3.0.4-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/6b30c854-b4ca-4700-aad1-073f3f8831f3/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.4.zip)

**Comment by idoco** [comment]
👍

**Review by onniaa — APPROVED** [review]

**Review by onniaa — APPROVED** [review]

**Review by onniaa — APPROVED** [review]

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/97494843-850c-4af6-a3cb-69ecfb3e44b7/artifacts/0/out/make/Loadmill-3.0.5-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/97494843-850c-4af6-a3cb-69ecfb3e44b7/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.0.5.zip)

**Pull request merged**
