### PR TITLE
🔥🕌 Firewall Proxy

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/2c8dcbd8-ba34-4a7d-afc9-85e403443ee6/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/2c8dcbd8-ba34-4a7d-afc9-85e403443ee6/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/85d745ef-53c6-4123-9136-0396df3bba95/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/85d745ef-53c6-4123-9136-0396df3bba95/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/1d9d01ec-803a-4ff9-8015-b6e2cfcbd4c7/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/1d9d01ec-803a-4ff9-8015-b6e2cfcbd4c7/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/541513c9-51e7-4d83-ac84-81edf32c6480/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/541513c9-51e7-4d83-ac84-81edf32c6480/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/dfd5c052-9bdb-4023-ac01-22ef82aba356/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/dfd5c052-9bdb-4023-ac01-22ef82aba356/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/157ad873-daf1-4c01-ada5-eedfac949124/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/157ad873-daf1-4c01-ada5-eedfac949124/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/f032cdca-7796-487e-8083-d554129d0af2/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/f032cdca-7796-487e-8083-d554129d0af2/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/107442bd-1de5-44df-98be-29327f30fa70/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/107442bd-1de5-44df-98be-29327f30fa70/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/c77fab6b-8c1d-4f6c-af7e-82be0212f67f/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c77fab6b-8c1d-4f6c-af7e-82be0212f67f/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/c3b44798-d89a-4010-8a69-5c7b3e361120/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c3b44798-d89a-4010-8a69-5c7b3e361120/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/a1519745-40d7-4599-a328-84d270665b16/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/a1519745-40d7-4599-a328-84d270665b16/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/61408d95-d16e-4498-9076-75f24d3ec269/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/61408d95-d16e-4498-9076-75f24d3ec269/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/81b0889f-5079-45bd-918c-3f9a92d3df08/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/81b0889f-5079-45bd-918c-3f9a92d3df08/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/52c18bd5-d760-4ba5-9ea7-0429bf487889/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/52c18bd5-d760-4ba5-9ea7-0429bf487889/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/7ce3ef50-e0ed-481b-8b83-fd99b3bcbf5d/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/7ce3ef50-e0ed-481b-8b83-fd99b3bcbf5d/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/cebaaf90-9d39-43b6-8dfa-957653af7af7/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/cebaaf90-9d39-43b6-8dfa-957653af7af7/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/4a1ad0a7-6799-488f-8c8e-fc92cdcc34a0/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/4a1ad0a7-6799-488f-8c8e-fc92cdcc34a0/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/44e008cd-69f3-466b-a87f-b0ab45d29fe6/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.24-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/44e008cd-69f3-466b-a87f-b0ab45d29fe6/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.24.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/012ccf8e-084d-4383-a5bd-182f14b49430/artifacts/0/out/make/Loadmill-3.3.24-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/012ccf8e-084d-4383-a5bd-182f14b49430/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.24.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
