### PR TITLE
🤵‍♀️ App Author Name

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/c8d0a364-5c81-403c-983a-0bc6da34bdc7/artifacts/0/out/make/Loadmill-3.3.5-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c8d0a364-5c81-403c-983a-0bc6da34bdc7/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.5.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/8a962738-5108-4444-a95d-cc37d747c945/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.5-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/8a962738-5108-4444-a95d-cc37d747c945/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.5.zip)

**Review by yanirta — APPROVED** [review]

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/499e6957-2dcd-4347-981d-ed88d0f6090b/artifacts/0/out/make/Loadmill-3.3.5-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/499e6957-2dcd-4347-981d-ed88d0f6090b/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.5.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/c28ae102-61b6-457d-96d9-888023b10d14/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.5-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/c28ae102-61b6-457d-96d9-888023b10d14/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.5.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
