### PR TITLE
🍏🤖 Auto Update for macOS build fix

### PR DESCRIPTION
**Pull request by Gilad-Gur-Andelman**

### CODE REVIEW

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/625dee67-9d53-45fc-b081-d9196556d060/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.20-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/625dee67-9d53-45fc-b081-d9196556d060/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.20.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/a7f50761-ef24-4b92-bf3e-b429c13db753/artifacts/0/out/make/Loadmill-3.3.21-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/a7f50761-ef24-4b92-bf3e-b429c13db753/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.21.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏗 MacOS Build Artifacts are available here👇 

### 1. [🍏 .dmg](https://output.circle-artifacts.com/output/job/91667fce-bfd1-441b-8aad-6230463c7b7b/artifacts/0/out/make/Loadmill-3.3.21-x64.dmg)

### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/91667fce-bfd1-441b-8aad-6230463c7b7b/artifacts/0/out/make/zip/darwin/x64/Loadmill-darwin-x64-3.3.21.zip)

**Comment by Gilad-Gur-Andelman** [comment]
## 🏠 Windows build Artifacts are available here👇 

### 1. [🪟 Setup.exe](https://output.circle-artifacts.com/output/job/b4fef831-7936-4e9f-8c36-ee6d8aaf0190/artifacts/0/out/make/squirrel.windows/x64/Loadmill-desktop-app-3.3.21-Setup.exe)
### 2. [🤐 .zip](https://output.circle-artifacts.com/output/job/b4fef831-7936-4e9f-8c36-ee6d8aaf0190/artifacts/0/out/make/zip/win32/x64/Loadmill-win32-x64-3.3.21.zip)

**Review by yigaldviri — APPROVED** [review]

**Pull request merged**
